config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'
  resources :questions, only: [:index, :show, :new, :create]
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
  end

  def new
    @question = Question.new
  end

  def create
    Question.create(question_params)
    redirect_to action: :index
  end

  private

  def question_params
    params.require(:question).permit(:title, :content, :name)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TechChat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&family=Roboto:wght@100&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class='header'>
        <div class='header-logo'>
          <%= link_to 'TechChat', root_path %>
        </div>
        <div class='header-button'>
          <%=link_to '質問する', new_question_path %>
        </div>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/questions/index.html.erb
<div class='index-main'>
  <div class='post-contents'>
    <% @questions.each do |question| %>
      <div class='post-content'>
        <div class='comment'>
          <div class='comment__num'>
            0
          </div>
          <div class='comment__unit'>
            comments
          </div>
        </div>

        <div class='question'>
          <div class='question-top'>
            <div class='question-top__title'>
              <%= link_to question.title, question_path(question.id), method: :get %>
            </div>
            <div class='question-top__name'>
              <%= question.name %>
            </div>
          </div>
          <div class='question-bottom'>
            <div class='question-bottom__content'>
              <%= question.content %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/new.html.erb
<div class='new-main'>
  <div class='form-contents'>
    <div class='form-header'></div>
    
    <div class='form-main'>
      <%= form_with model: @question, local: true do |form| %>
        <div class='input-items'>
          <div class='form-title'>
          <%= form.text_field :title, placeholder: "タイトル" %>
          </div>
          <div class='form-content'>
            <%= form.text_area :content, placeholder: "質問内容" %><br>
          </div>    
          <div class='form-name'>
            <%= form.text_field :name, placeholder: "投稿者名" %>
          </div>
          <div class='submit-button'>
            <%= form.submit 'POST'%>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/show.html.erb
タイトル：<%= @question.title %><br>
質問内容：<%= @question.name %><br>
投稿者名：<%= @question.content %>